### ISSUE TITLE
Chinese Messy code.

### ISSUE THREAD

**Issue by simphonydeveloper** [erikn69/ZplEscPrinter#2]
![image](https://github.com/user-attachments/assets/756d0f0b-ed87-40b4-a40e-757d9f87928d)
when i send Chinese character is bad.
Can i how to do?
thanks

**Comment by erikn69** [comment]
I'm sorry, I don't know how to use those characters, and I wouldn't know how to add it, I imagine that a font is needed, but this little repo is for personal tests.

**Comment by simphonydeveloper** [comment]
you can send `这是测试`  to zlescprinter.

**Comment by simphonydeveloper** [comment]
Okay, because I don't really understand Node.js. But your creativity is great.

**Comment by erikn69** [comment]
`btoa` fails for me

![image](https://github.com/user-attachments/assets/01be87bb-44f4-47c8-a055-8590314c3d0e)
https://github.com/erikn69/ZplEscPrinter/blob/afdb6f1717a152dafc03f8bf73cf0f497620bcdc/ZplEscPrinter/js/main.js#L172

**Comment by simphonydeveloper** [comment]
It doesn't seem to solve the problem. I tested version 3.0.3

**Comment by erikn69** [comment]
So, I can't replicate your bug, with https://github.com/erikn69/ZplEscPrinter/commit/8ea3c056af20e6d05eae6714cb317cac6ffd266d everything works for me

![image](https://github.com/user-attachments/assets/6e0ab956-b53c-4388-b1f2-9d3e6b719551)

**Comment by simphonydeveloper** [comment]
thank you .
Can you help test this content?
Regards
```txt
90003 Peter                             
----------------------------------------
CHK 8016    TBL 21/1                    
               GST 1                    
          13 Nov'24 10:55 下午            
----------------------------------------
 1 Cold Cut              458.00 T1      
   法式冷切拼盘                               
 1 Cold Cut              458.00 T1      
   法式冷切拼盘                               
 1 Scallops Caviar       328.00 T1      
   扇贝鱼子酱                                
 1 Joselito              580.00 T1      
   小何塞火腿                                
                                        
   Subtotal               1‚824.00      
   T1 6%                    109.44      
   Payment                1‚933.44      
   微信                   1‚933.44        
                                        
  ----------- Check Closed -----------  
          13 Nov'24 10:55 下午           
```

**Comment by erikn69** [comment]
![image](https://github.com/user-attachments/assets/89f5aa74-271b-4c02-8fa7-0deafbea0faa)

**Comment by simphonydeveloper** [comment]
I sent it using Postman. How did you send it?

**Comment by erikn69** [comment]
You can't use postman for ESCPOS, it's not an API, it's a raw emulator, you should print raw text, 
On Windows I usually create a raw printer pointing to the IP/Port of the emulator
![image](https://github.com/user-attachments/assets/4dfc446d-2aa7-491b-b73a-9df15cad795a)

But for testing purposes 
![image](https://github.com/user-attachments/assets/be7237e1-112f-4398-8349-15815a03d38b)

![image](https://github.com/user-attachments/assets/391ac80a-aa07-40d7-8cc5-9f714f99bf62)

**Comment by erikn69** [comment]
[v3.0.4](https://github.com/erikn69/ZplEscPrinter/releases/tag/v3.0.4)
